services:
  kanidmd:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-8443}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PROTO: ${VIRTUAL_PROTO:-https}
      KANIDM_TLS_CHAIN: ${KANIDM_TLS_CHAIN:-/certs/${VIRTUAL_HOST}/fullchain.pem}
      KANIDM_TLS_KEY: ${KANIDM_TLS_KEY:-/certs/${VIRTUAL_HOST}/key.pem}
    volumes:
      - letsencrypt-certs:/certs
    networks:
      - letsencrypt-network

volumes:
  letsencrypt-certs:
    external: true

networks:
  letsencrypt-network:
    name: letsencrypt-network
    external: true