[paths]
environments_path = "./environments"
extensions_dirs = []

[build]
copy_additional_files = true
env_file_patterns = [".env", "override.css"]

[build.environments]
available = ["forwarding", "letsencrypt", "step-ca"]
